name: ci

on:
  push:
  pull_request:

jobs:
  pkgbuild-validate:
    runs-on: ubuntu-latest
    name: Validate a Pull Request
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build pkg
        id: makepkg
        uses: edlanglois/pkgbuild-action@v1
        with:
          pkgdir: 'pkg/fuf-git'
      - name: print results
        run: |
          echo "Successfully created the following package archive"
          echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
