name: build pkgbuild

on:
  push:
  pull_request:

jobs:
  pkgbuild-validate:
    runs-on: ubuntu-latest
    name: Validate a Pull Request
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: update pkgver
        run: |
          sed -i "s/pkgver=.*/pkgver=$(git describe --long --tags | sed -r 's/([^-]*-g)/r\1/;s/-/./g;s/^v//g')/g" pkg/fuf-bin/PKGBUILD
          sed -i "s/pkgver =.*/pkgver = $(git describe --long --tags | sed -r 's/([^-]*-g)/r\1/;s/-/./g;s/^v//g')/g" pkg/fuf-bin/.SRCINFO
      - name: build pkg
        id: makepkg
        uses: edlanglois/pkgbuild-action@v1
        with:
          pkgdir: 'pkg/fuf-bin'
      - name: print results
        run: |
          echo "successfully created the following package archive"
          echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
